org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Versions
minecraft_version=26.2
minecraft_version_range=[26.2,27.0)
neo_version=26.2.0.59
neo_version_range=[26.2,)

# Mod Properties
mod_id=bloodrunes
mod_name=Vikings: Blood & Runes
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.denmoth.bloodrunes
mod_authors=Denmoth
mod_description=Vikings: Blood & Runes Mod for Minecraft 26.2
org.gradle.java.home=/Users/denmoth8871/.gemini/antigravity/scratch/jdk21/Contents/Home
